// <auto-generated />
namespace resource_dashboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class attemptdos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attemptdos));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132045266_attempt-dos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
